### ISSUE TITLE
Tracking issue: VS Code Visual Tests

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-common#729]
This is tracking issue for VS Code Visual Tests

- [x] Basic checks - start, stop
- [x] Test if analytics extension can be found
- [x] Test if analytics extension can be installed
- [x] Extension + Python project
- [x] Extension + Maven project
- [x] CVE display

(sub-issues to be opened for each point described above)

**Comment by tisnik** [comment]
This is implemented there:
https://github.com/fabric8-analytics/fabric8-analytics-common/tree/master/vscode-visual-tests
