### ISSUE TITLE
Create sample projects to be used by Analytics plugin

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-common#891]
This is a tracking issue, that needs to be divided into sub-tasks.

The following project files needs to be created:

### NPM ecosystem (`package.json`):

- [x] project without any dependencies #905
- [x] project with one dependency without CVE #906
- [x] project with one dependency with CVE #918
- [x] project with five depencencies without CVE #907
- [x] project with five depencencies, one CVE #908
- [x] project with five depencencies, two CVEs #909
- [x] project with five depencencies, three CVEs #927
- [x] project with five depencencies, four CVEs #928
- [x] project with five depencencies, five CVEs #910

### Maven ecosystem (`pom.xml`):

- [x] project without any dependencies
- [x] project with one dependency without CVE #920 
- [x] project with one dependency with CVE #921
- [x] project with five depencencies without CVE #923
- [x] project with five depencencies, one CVE #924
- [x] project with five depencencies, two CVEs #925 
- [x] project with five depencencies, three CVEs #926
- [x] project with five depencencies, four CVEs #929
- [x] project with five depencencies, five CVEs #930

### Acceptance criteria:

- These projects will be part of VSCode visual tests subproject in this repository
